### ISSUE TITLE
Issues with profile pandas pivot

### ISSUE THREAD

**Issue by ethlau** [lmachadopolettivalle/camels-database-schemas#14]
Hi @lmachadopolettivalle,

Running the sample_end_to_end.py returns the following error:

```
Traceback (most recent call last):
  File "/Users/ethlau/Research/CAMELS/camels-database-schemas/sample_end_to_end.py", line 35, in <module>
    profiles_result = profiles_result.pivot(index="radius", columns="halo_unique_id", values="property_value")
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 6876, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/reshape/pivot.py", line 461, in pivot
    return indexed.unstack(columns)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/series.py", line 3826, in unstack
    return unstack(self, level, fill_value)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 430, in unstack
    unstacker = _Unstacker(
  File "/usr/local/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 118, in __init__
    self._make_selectors()
  File "/usr/local/lib/python3.9/site-packages/pandas/core/reshape/reshape.py", line 167, in _make_selectors
    raise ValueError("Index contains duplicate entries, cannot reshape")
ValueError: Index contains duplicate entries, cannot reshape
```

Seems that the reason is that there are duplicated entries in 'radius', which is used as index of the reshaped table.

**Comment by lmachadopolettivalle** [comment]
With the latest PR #16 , we are now using the FoF halo IDs provided by IllustrisTNG and SIMBA. Note that the combination (haloID, snapshot, simulation_unique_id) is the unique identifier of any given FoF halo. In fact, there are several halos with haloID == 0, but only one such halo at any given simulation + snapshot combination.
